routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/cache-clear', function(){
   // \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    \Illuminate\Support\Facades\Artisan::call('migrate');
});
Route::middleware(['auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/test-api', 'TestController@index');
    Route::get('/test-api/cities', 'TestController@getCities');

    Route::resource('/users', 'UserController');
    
    //Route for Master Adjuster

    Route::resource('/adjusters', 'MasterAdjusterController');
    
    Route::post('/adjustermasterslug', 'AjaxController@adjustermasterslug')->name('adjustermasterslug');
    Route::get('/master-fields', 'MasterFieldAccessController@masterfields')->name('masterfields');
    Route::post('/master-fields/store', 'MasterFieldAccessController@store')->name('store');    
    //Routes for Personal Reasons
    Route::resource('/inactive-reasons', 'PersonalInactiveReasonController');
    
    //Routes for state/state service areas
    Route::resource('/states', 'StateController');
    
    //Routes for state/state service areas
    Route::resource('/cities', 'CityController');
    
    //Route for service state area
    Route::resource('/service-state-area', 'ServiceStateAreaController');
    
    //Routes for adjuster grade
    Route::resource('/adjuster-grades', 'AdjusterGradeController');
    
    //Routes for grade reasons
    Route::resource('/grade-reasons', 'GradeReasonController');
    
    //Routes for home states
    Route::resource('/home-state-license', 'AdjusterHomeStateLicenseController');
    Route::get('/home-state-license/single/edit/{state_license}', 'AdjusterHomeStateLicenseController@editSingle')->name('home-state-license-single.edit');
    
    //Route for role
    Route::resource('/roles', 'RoleController');
    
    //Route for search adjuster
    Route::get('/search/adjuster', 'SearchAdjusterController@index')->name('search.adjuster.index');
    Route::post('/search/adjuster', 'SearchAdjusterController@search')->name('search.adjuster');
    
    //Route for supporting forms main file
    Route::get('/supporting-forms', 'SupportingFormController@index')->name('supporting.form.index');
    
    //Routes for Languages
    Route::resource('/languages', 'LanguageController');
    
    //Routes for specialities
    Route::resource('/specialties', 'SpecialityController');
    
    //Route for carriers
    Route::resource('/carriers', 'CarrierController');
    
    //Route for Field Assign Source
    Route::resource('/field-assign-sources', "FieldAssignSourceController");
    
    //Route for Cl Assign Type
    Route::resource('/cl-assign-types', "ClAssignTypeController");

    //Route for personal status
    Route::resource('/personal-status', 'PersonalStatusController');
    
    //Route for Adjuster Correction
    Route::resource('/adjuster-corrections', "AdjusterCorrectionController");
    
    //Route for correction rejections
    Route::resource('/correction-rejections', 'CorrectionRejectionController');
    
    //Route for Log assignments
    Route::resource('/log-assignment', 'LogAssignmentController');

    Route::get('/log-fields', 'LogFieldAccessController@logfields')->name('logfields');
    Route::post('/log-fields/store', 'LogFieldAccessController@logstore')->name('logstore');
    
    //Routes for Claim Status
    Route::resource('/claim-status', 'ClaimStatusController');
    
    //Route for Tabs
    Route::get('/adjuster/{adjuster_id}/home-states', 'TabController@homeStates')->name('tab.adjuster.homestate');
    Route::get('/adjuster/{adjuster_id}/corrections', 'TabController@corrections')->name('tab.adjuster.corrections');
    Route::get('/adjuster/{adjuster_id}/rejections', 'TabController@rejections')->name('tab.adjuster.rejections');
    Route::get('/adjuster/{adjuster_id}/log-assignments', 'TabController@logAssignment')->name('tab.adjuster.log-assignments');
    Route::get('/adjuster/{adjuster_id}/claim-status', 'TabController@claimStatus')->name('tab.adjuster.claim-status');
    
    
    Route::get('/manage-dashboard', 'DashboardItemController@index')->name('dashboard.item.index');
    Route::post('/save-user-dashboard-item', 'DashboardItemController@store')->name('dashboard.item.user.store');

    //ajax routes
    Route::post('/get-cities', 'AjaxController@getCities')->name('get.cities');
    
});

app/Models/PersonalStatus.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PersonalStatus extends Model
{
    protected $guarded = [];
    protected $table = 'personal_status';
}

app/Http/Controllers/PersonalStatusController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PersonalStatusRequest;
use App\Models\PersonalStatus;
use Illuminate\Http\Request;

class PersonalStatusController extends Controller
{
    public function index(){
        $personal_statuses = PersonalStatus::all();

        return view('supporting-forms.personal-status.index', compact('personal_statuses'));
    }

    public function create(){
        return view('supporting-forms.personal-status.create');
    }

    public function store(PersonalStatusRequest $request) {
        PersonalStatus::create([
            'name' => $request->name
        ]);
        
        return redirect()->route('personal-status.index')->with([
            'status' => 'success',
            'message' => 'Personal status has been created.'
        ]);
    }

    public function edit($id){
        $personal_status = PersonalStatus::findOrFail($id);
        return view('supporting-forms.personal-status.edit', compact('personal_status'));
    }

    public function update(PersonalStatusRequest $request, $id){
        $personal_status = PersonalStatus::findOrFail($id);
        $personal_status->update([
            'name' => $request->name
        ]);

        return back()->with([
            'status' => 'success',
            'message' => 'Personal status has been updated.'
        ]);
    }

    public function destroy($id){
        $personal_status = PersonalStatus::findOrFail($id);
        $personal_status->delete();
        return redirect()->route('personal-status.index')->with([
            'status' => 'success',
            'message' => 'Personal status has been deleted.'
        ]);
    }
}

app/Http/Controllers/SupportingFormController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SupportingFormController extends Controller
{
    public function index(){
        return view('supporting-forms.index');
    }
}

resources/views/supporting-forms/personal-status/create.blade.php
@extends('adminlte::page')
@section('title', 'Add Perosnnel Status')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Add New Personnel Status</h3>
        </div>
        <form action="{{ route('personal-status.store') }}" method="POST">
            @csrf
            <div class="box-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            <label>Name:</label>
                            <input type="text" name="name" class="form-control">
                            @if($errors->has('name'))
                                <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btnTheme">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/supporting-forms/personal-status/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Personnel Status')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Edit Personnel Status</h3>
        </div>
        <form action="{{ route('personal-status.update', $personal_status->id) }}" method="POST">
            @csrf
            {{ method_field('PUT') }}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            <label>Reason</label>
                            <input type="text" name="name" value="{{ $personal_status->name }}" class="form-control">
                            @if($errors->has('name'))
                                <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btnTheme">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/supporting-forms/personal-status/index.blade.php
@extends('adminlte::page')
@section('title', 'All Personnel Status')

@section('content')
    <div class="box">
        <div class="box-header">
            <div class="col-md-6">
                <h3 class="box-title">All Personnel Status</h3>
            </div>
            <div class="col-md-6 text-right">
                <a href="{{ route('inactive-reasons.create') }}" class="btn btn-primary btnTheme">Create Personnel Status</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="client" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Sr#</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @if(!empty($personal_statuses))
                    @foreach($personal_statuses as $personal_status)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $personal_status->name ?? '--' }}</td>
                            <td>
                                <a href="{{ route('personal-status.edit', $personal_status->id) }}"><button class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-pencil"></i></button></a>
                                {{--<a href="#"><button class="btn btn-xs btn-success"><i class="fa fa-eye"></i></button></a>--}}
                                <form action="{{ route('personal-status.destroy', $personal_status->id) }}" method="POST" class="delete_item">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-xs btn-danger" data-toggle="tooltip" title="Delete"><i class="glyphicon glyphicon-remove"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

@push('js')
    <script type="text/javascript">
        $(function () {
            $('#client').DataTable({
                'lengthChange': false,
            })

        });
    </script>
@endpush