routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/cache-clear', function(){
   // \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    \Illuminate\Support\Facades\Artisan::call('migrate');
});
Route::middleware(['auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/test-api', 'TestController@index');
    Route::get('/test-api/cities', 'TestController@getCities');

    Route::resource('/users', 'UserController');
    
    //Route for Master Adjuster

    Route::resource('/adjusters', 'MasterAdjusterController');
    
    Route::post('/adjustermasterslug', 'AjaxController@adjustermasterslug')->name('adjustermasterslug');
    Route::get('/master-fields', 'MasterFieldAccessController@masterfields')->name('masterfields');
    Route::post('/master-fields/store', 'MasterFieldAccessController@store')->name('store');    
    //Routes for Personal Reasons
    Route::resource('/inactive-reasons', 'PersonalInactiveReasonController');
    
    //Routes for state/state service areas
    Route::resource('/states', 'StateController');
    
    //Routes for state/state service areas
    Route::resource('/cities', 'CityController');
    
    //Route for service state area
    Route::resource('/service-state-area', 'ServiceStateAreaController');
    
    //Routes for adjuster grade
    Route::resource('/adjuster-grades', 'AdjusterGradeController');
    
    //Routes for grade reasons
    Route::resource('/grade-reasons', 'GradeReasonController');
    
    //Routes for home states
    Route::resource('/home-state-license', 'AdjusterHomeStateLicenseController');
    Route::get('/home-state-license/single/edit/{state_license}', 'AdjusterHomeStateLicenseController@editSingle')->name('home-state-license-single.edit');
    
    //Route for role
    Route::resource('/roles', 'RoleController');
    
    //Route for search adjuster
    Route::get('/search/adjuster', 'SearchAdjusterController@index')->name('search.adjuster.index');
    Route::post('/search/adjuster', 'SearchAdjusterController@search')->name('search.adjuster');
    
    //Route for supporting forms main file
    Route::get('/supporting-forms', 'SupportingFormController@index')->name('supporting.form.index');
    
    //Routes for Languages
    Route::resource('/languages', 'LanguageController');
    
    //Routes for specialities
    Route::resource('/specialties', 'SpecialityController');
    
    //Route for carriers
    Route::resource('/carriers', 'CarrierController');
    
    //Route for Field Assign Source
    Route::resource('/field-assign-sources', "FieldAssignSourceController");
    
    //Route for Cl Assign Type
    Route::resource('/cl-assign-types', "ClAssignTypeController");

    //Route for personal status
    Route::resource('/personal-status', 'PersonalStatusController');
    
    //Route for Adjuster Correction
    Route::resource('/adjuster-corrections', "AdjusterCorrectionController");
    
    //Route for correction rejections
    Route::resource('/correction-rejections', 'CorrectionRejectionController');
    
    //Route for Log assignments
    Route::resource('/log-assignment', 'LogAssignmentController');

    Route::get('/log-fields', 'LogFieldAccessController@logfields')->name('logfields');
    Route::post('/log-fields/store', 'LogFieldAccessController@logstore')->name('logstore');
    
    //Routes for Claim Status
    Route::resource('/claim-status', 'ClaimStatusController');
    
    //Route for Tabs
    Route::get('/adjuster/{adjuster_id}/home-states', 'TabController@homeStates')->name('tab.adjuster.homestate');
    Route::get('/adjuster/{adjuster_id}/corrections', 'TabController@corrections')->name('tab.adjuster.corrections');
    Route::get('/adjuster/{adjuster_id}/rejections', 'TabController@rejections')->name('tab.adjuster.rejections');
    Route::get('/adjuster/{adjuster_id}/log-assignments', 'TabController@logAssignment')->name('tab.adjuster.log-assignments');
    Route::get('/adjuster/{adjuster_id}/claim-status', 'TabController@claimStatus')->name('tab.adjuster.claim-status');
    
    
    Route::get('/manage-dashboard', 'DashboardItemController@index')->name('dashboard.item.index');
    Route::post('/save-user-dashboard-item', 'DashboardItemController@store')->name('dashboard.item.user.store');

    //ajax routes
    Route::post('/get-cities', 'AjaxController@getCities')->name('get.cities');
    
});

app/Models/AdjusterStateLicense.php
<?php

namespace App\Models;

use Carbon\Carbon;
use DateTime;
use Illuminate\Database\Eloquent\Model;

class AdjusterStateLicense extends Model
{
    protected $table = 'adjuster_state_licenses';
    protected $guarded = [];

    public function state(){
        return $this->belongsTo(State::class, 'state_id', 'id');
    }

    public function adjuster(){
        return $this->belongsTo(MasterAdjuster::class, 'master_adjuster_id', 'id');
    }

    public function setExpiryDateAttribute($value){
        $datetime = DateTime::createFromFormat('m-d-Y', $value);
        return $this->attributes['expiry_date'] = $datetime->format('Y-m-d');
    }

    public function getExpiryDateAttribute($value){
        return Carbon::parse($value)->format('m-d-Y');
    }
}

resources/views/adjuster-state-license/create.blade.php
@extends('adminlte::page')
@section('title', 'Adjuster Home State License Form')

@section('content')
    <div class="box">
        <div class="box-header customHeader">
            <h3 class="box-title">Adjuster Home State License Form</h3>
        </div>
        <form action="{{ route('home-state-license.store') }}" method="POST">
            @csrf
            <div class="box-body">
                <div class="row">
                    <div class="stateForm">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group {{ $errors->has('adjuster') ? 'has-error': '' }}">
                                    <label>Select Adjuster</label>
                                    <select name="adjuster" class="form-control license-states">
                                        @if(!empty($adjusters))
                                            @foreach($adjusters as $adjuster)
                                                <option
                                                        value="{{ $adjuster->id }}">{{ $adjuster->getFullName() }}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                    @if($errors->has('license_state'))
                                        <span
                                                class="help-block text-danger">{{ $errors->first('license_state') }}</span>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group {{ $errors->has('npn_number') ? 'has-error': '' }}">
                                            <label>NPN Number</label>
                                            <input type="text" name="npn_number" class="form-control"
                                                   value="">
                                            @if($errors->has('npn_number'))
                                                <span
                                                        class="help-block text-danger">{{ $errors->first('npn_number') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group {{ $errors->has('expiry_date') ? 'has-error': '' }}">
                                            <label>License Expiry Date</label>
                                            <input type="text" name="expiry_date" class="form-control datepicker"
                                                   value="">
                                            @if($errors->has('expiry_date'))
                                                <span
                                                        class="help-block text-danger">{{ $errors->first('expiry_date') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group {{ $errors->has('license_state') ? 'has-error': '' }}">
                                            <label>License State</label>
                                            <select name="license_state" class="form-control license-states">
                                                @if(!empty($states))
                                                    @foreach($states as $state)
                                                        <option
                                                                value="{{ $state->id }}">{{ $state->name }}</option>
                                                    @endforeach
                                                @endif
                                            </select>
                                            @if($errors->has('license_state'))
                                                <span
                                                        class="help-block text-danger">{{ $errors->first('license_state') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div
                                                class="form-group {{ $errors->has('license_number') ? 'has-error': '' }}">
                                            <label>License Number</label>
                                            <input type="text" name="license_number" class="form-control"
                                                   value="">
                                            @if($errors->has('license_number'))
                                                <span
                                                        class="help-block text-danger">{{ $errors->first('license_number') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label style="display: block;">&nbsp;</label>
                                            <label><input type="checkbox" class="home-states" name="home_state"
                                                          value="1"><b> Home
                                                    State</b> </label>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label style="display: block;">&nbsp;</label>
                                            <label><input type="radio" name="active" value="1" checked>
                                                Active </label> <br>
                                            <label><input type="radio" name="active" value="0">
                                                InActive </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-md-9">
                                <div class="form-group">
                                    <label for="">Comment</label>
                                    <textarea class="form-control" rows="5"
                                              name="comment"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary btnTheme">Submit</button>
                </div>
        </form>
    </div>
@endsection

resources/views/adjuster-state-license/edit-single.blade.php
@extends('adminlte::page')
@section('title', 'Adjuster Home State License Form')

@section('content')
    <div class="box">
        <div class="box-header customHeader">
            <h3 class="box-title">Edit State License</h3>
        </div>
        <div class="box-body">
            <form action="{{ route('home-state-license.update', $license->id) }}" method="POST">
                @csrf
                {{ method_field("PUT") }}
                <input type="hidden" name="adjuster_id" value="{{ $license->adjuster->id }}"/>
                <div class="stateForm">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group {{ $errors->has('npn_number') ? 'has-error': '' }}">
                                        <label>NPN Number</label>
                                        <input type="text" name="npn_number" class="form-control"
                                               value="{{ $license->npn_number }}">
                                        @if($errors->has('npn_number'))
                                            <span
                                                    class="help-block text-danger">{{ $errors->first('npn_number') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group {{ $errors->has('expiry_date') ? 'has-error': '' }}">
                                        <label>License Expiry Date</label>
                                        <input type="text" name="expiry_date" class="form-control datepicker"
                                               value="{{ $license->expiry_date }}">
                                        @if($errors->has('expiry_date'))
                                            <span
                                                    class="help-block text-danger">{{ $errors->first('expiry_date') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group {{ $errors->has('license_state') ? 'has-error': '' }}">
                                        <label>License State</label>
                                        <select name="license_state" class="form-control license-states">
                                            @if(!empty($states))
                                                @foreach($states as $state)
                                                    <option
                                                            value="{{ $state->id }}" {{ ($license->state_id == $state->id) ? 'selected' : '' }}>{{ $state->name }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                        @if($errors->has('license_state'))
                                            <span
                                                    class="help-block text-danger">{{ $errors->first('license_state') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div
                                            class="form-group {{ $errors->has('license_number') ? 'has-error': '' }}">
                                        <label>License Number</label>
                                        <input type="text" name="license_number" class="form-control"
                                               value="{{ $license->license_number }}">
                                        @if($errors->has('license_number'))
                                            <span
                                                    class="help-block text-danger">{{ $errors->first('license_number') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label style="display: block;">&nbsp;</label>
                                        <label><input type="checkbox" class="home-states" name="home_state"
                                                      {{ ($license->home_state == 1) ? 'checked' : ''  }} value="1"><b> Home
                                                State</b> </label>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label style="display: block;">&nbsp;</label>
                                        <label><input type="radio" name="active"
                                                      {{ ($license->active == 1) ? 'checked' : ''  }} value="1">
                                            Active </label> <br>
                                        <label><input type="radio" name="active"
                                                      {{ ($license->active == 0) ? 'checked' : ''  }} value="0">
                                            InActive </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-9">
                            <div class="form-group">
                                <label for="">Comment</label>
                                <textarea class="form-control" rows="5"
                                          name="comment">{{ $license->comment }}</textarea>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label style="display: block; margin-top: 90px;">&nbsp;</label>
                            <button class="btn btn-success" type="submit">Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $(".home-states").click(function () {
            var data_id = $(this).data('id');
            $(".home-states").each(function () {
                if ($(this).data('id') != data_id) {
                    $(this).prop('checked', false);
                } else {
                    $(this).attr('checked', true);
                }
            });
        });
    </script>
@endpush

resources/views/adjuster-state-license/index.blade.php
@extends('adminlte::page')
@section('title', 'Home State License')

@section('content')
    <div class="box">
        <div class="box-header">
            <div class="col-md-6">
                <h3 class="box-title">Adjuster State License</h3>
            </div>
            <div class="col-md-6 text-right">
                <a href="{{ route('home-state-license.create') }}" class="btn btn-primary btnTheme">Create State License</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="client" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Total License</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @if(!empty($adjusters))
                    @foreach($adjusters as $adjuster)
                        <tr>
                            <td>{{ $adjuster->id }}</td>
                            <td>{{ $adjuster->getFullName() }}</td>
                            <td>
                                @if(!empty($adjuster->types))
                                    @foreach($adjuster->types as $key => $type)
                                        {{ $type->name }}
                                        @if($key >= 0 && $key < count($adjuster->types) - 1)
                                            ,
                                        @endif
                                    @endforeach
                                @endif
                            </td>
                            <td>{{ $adjuster->home_state_licenses()->count() }}</td>
                            <td>
                                <a href="{{ route('home-state-license.edit', $adjuster->id) }}"><button class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-pencil"></i></button></a>
                                <a href="{{ route('home-state-license.show', $adjuster->id) }}"><button class="btn btn-xs btn-success"><i class="fa fa-eye"></i></button></a>
                                <form action="{{ route('home-state-license.destroy', $adjuster->id) }}" method="POST" class="delete_item">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-xs btn-danger" data-toggle="tooltip" title="Delete"><i class="glyphicon glyphicon-remove"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

@push('js')
    <script type="text/javascript">
        $(function () {
            $('#client').DataTable({
                'lengthChange': true,
                'pagelength': 10
            })

        });
    </script>
@endpush

resources/views/adjuster-state-license/show.blade.php
@extends('adminlte::page')
@section('title', 'TSI LOG ASSIGNMENT FORM')

@section('content')
    <div class="box">
        <div class="box-header customHeader">
            <h3 class="box-title"><b>{{ $adjuster->getFullName() ?? "-" }} - {{ $adjuster->state->name ?? "-" }}</b></h3>
            <a href="{{ route('adjusters.edit', $adjuster->id) }}" style="float:right; color:white;">Edit</a>
        </div>
        <div class="col-md-12" style="padding: 10px;">
            {{-- <div class="col-md-1"></div> --}}
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('adjusters.show', $adjuster->id) }}" class="btn btn-primary btnTheme" >Adjuster Data</a>
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('tab.adjuster.homestate', $adjuster->id) }}" class="btn btn-primary btnTheme" style="background-color: #dd4b39 !important;border-color: #dd4b39 !important;">State Licenses</a>
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('tab.adjuster.corrections', $adjuster->id) }}" class="btn btn-primary btnTheme">Corrections</a>
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('tab.adjuster.rejections', $adjuster->id) }}" class="btn btn-primary btnTheme">Rejections</a>
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('tab.adjuster.log-assignments', $adjuster->id) }}" class="btn btn-primary btnTheme">Claim Log Assignments</a>
            <a href="{{ route('tab.adjuster.claim-status', $adjuster->id) }}" class="btn btn-primary btnTheme">Claim Status</a>

        </div>
        <div class="clearfix"></div>
        <div class="box-body table-responsive no-padding">
            <div class="box-header customHeader">
                <h3 class="box-title"><b>State Licenses</b></h3>
            </div>
            <table class="table table-bordered tableStyle">
                <tbody>
                <tr>
                    <th>First Name</th>
                    <td>{{ $adjuster->first_name ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Last Name</th>
                    <td>{{ $adjuster->last_name ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Date of Birth</th>
                    <td>{{ $adjuster->dob ?? "-" }}</td>
                </tr>
                <tr>
                    <th>City</th>
                    <td>{{ $adjuster->city->name ?? '-' }}</td>
                </tr>
                <tr>
                    <th>State</th>
                    <td>{{ $adjuster->state->name ?? "-" }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    @if(!empty($adjuster->home_state_licenses))
        @foreach($adjuster->home_state_licenses as $state_license)
            <div class="box">
                <div class="box-header customHeader">
                    <h3 class="box-title">{{ ($state_license->home_state === 1) ? 'Home State: ' : '' }} {{ $state_license->state->name }} </h3>
                    <a href="{{ route('home-state-license-single.edit', $state_license->id) }}" style="float:right; color:white;">Edit</a>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-bordered tableStyle">
                        <tbody>
                        <tr>
                            <th>License State</th>
                            <td>{{ $state_license->state->name ?? "-" }}</td>
                        </tr>
                        <tr>
                            <th>License Number</th>
                            <td>{{ $state_license->license_number ?? "-" }}</td>
                        </tr>
                        <tr>
                            <th>Expiry Data</th>
                            <td>{{ $state_license->expiry_date ?? "-" }}</td>
                        </tr>
                        <tr>
                            <th>NPN Number</th>
                            <td>{{ $state_license->npn_number ?? '-' }}</td>
                        </tr>
                        <tr>
                            <th>Home State</th>
                            <td>{{ ($state_license->home_state === 1) ? 'Yes' : 'No' }}</td>
                        </tr>
                        <tr>
                            <th>Active/Not Active</th>
                            <td>{{ ($state_license->active === 1) ? 'Active' : 'Not Active' }}</td>
                        </tr>
                        <tr>
                            <th>Comment</th>
                            <td>{{ $state_license->comment ?? "-" }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        @endforeach
    @endif
@endsection

@push('css')
    <style type="text/css">
        .tableStyle th {
            width: 20%;
        }
    </style>
@endpush