routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/cache-clear', function(){
   // \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    \Illuminate\Support\Facades\Artisan::call('migrate');
});
Route::middleware(['auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/test-api', 'TestController@index');
    Route::get('/test-api/cities', 'TestController@getCities');

    Route::resource('/users', 'UserController');
    
    //Route for Master Adjuster

    Route::resource('/adjusters', 'MasterAdjusterController');
    
    Route::post('/adjustermasterslug', 'AjaxController@adjustermasterslug')->name('adjustermasterslug');
    Route::get('/master-fields', 'MasterFieldAccessController@masterfields')->name('masterfields');
    Route::post('/master-fields/store', 'MasterFieldAccessController@store')->name('store');    
    //Routes for Personal Reasons
    Route::resource('/inactive-reasons', 'PersonalInactiveReasonController');
    
    //Routes for state/state service areas
    Route::resource('/states', 'StateController');
    
    //Routes for state/state service areas
    Route::resource('/cities', 'CityController');
    
    //Route for service state area
    Route::resource('/service-state-area', 'ServiceStateAreaController');
    
    //Routes for adjuster grade
    Route::resource('/adjuster-grades', 'AdjusterGradeController');
    
    //Routes for grade reasons
    Route::resource('/grade-reasons', 'GradeReasonController');
    
    //Routes for home states
    Route::resource('/home-state-license', 'AdjusterHomeStateLicenseController');
    Route::get('/home-state-license/single/edit/{state_license}', 'AdjusterHomeStateLicenseController@editSingle')->name('home-state-license-single.edit');
    
    //Route for role
    Route::resource('/roles', 'RoleController');
    
    //Route for search adjuster
    Route::get('/search/adjuster', 'SearchAdjusterController@index')->name('search.adjuster.index');
    Route::post('/search/adjuster', 'SearchAdjusterController@search')->name('search.adjuster');
    
    //Route for supporting forms main file
    Route::get('/supporting-forms', 'SupportingFormController@index')->name('supporting.form.index');
    
    //Routes for Languages
    Route::resource('/languages', 'LanguageController');
    
    //Routes for specialities
    Route::resource('/specialties', 'SpecialityController');
    
    //Route for carriers
    Route::resource('/carriers', 'CarrierController');
    
    //Route for Field Assign Source
    Route::resource('/field-assign-sources', "FieldAssignSourceController");
    
    //Route for Cl Assign Type
    Route::resource('/cl-assign-types', "ClAssignTypeController");

    //Route for personal status
    Route::resource('/personal-status', 'PersonalStatusController');
    
    //Route for Adjuster Correction
    Route::resource('/adjuster-corrections', "AdjusterCorrectionController");
    
    //Route for correction rejections
    Route::resource('/correction-rejections', 'CorrectionRejectionController');
    
    //Route for Log assignments
    Route::resource('/log-assignment', 'LogAssignmentController');

    Route::get('/log-fields', 'LogFieldAccessController@logfields')->name('logfields');
    Route::post('/log-fields/store', 'LogFieldAccessController@logstore')->name('logstore');
    
    //Routes for Claim Status
    Route::resource('/claim-status', 'ClaimStatusController');
    
    //Route for Tabs
    Route::get('/adjuster/{adjuster_id}/home-states', 'TabController@homeStates')->name('tab.adjuster.homestate');
    Route::get('/adjuster/{adjuster_id}/corrections', 'TabController@corrections')->name('tab.adjuster.corrections');
    Route::get('/adjuster/{adjuster_id}/rejections', 'TabController@rejections')->name('tab.adjuster.rejections');
    Route::get('/adjuster/{adjuster_id}/log-assignments', 'TabController@logAssignment')->name('tab.adjuster.log-assignments');
    Route::get('/adjuster/{adjuster_id}/claim-status', 'TabController@claimStatus')->name('tab.adjuster.claim-status');
    
    
    Route::get('/manage-dashboard', 'DashboardItemController@index')->name('dashboard.item.index');
    Route::post('/save-user-dashboard-item', 'DashboardItemController@store')->name('dashboard.item.user.store');

    //ajax routes
    Route::post('/get-cities', 'AjaxController@getCities')->name('get.cities');
    
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\DashboardItem;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name','user_name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function role()
    {
        return $this->belongsTo(Models\Role::class, 'role_id');
    }

    public function dashboard_items(){
        return $this->belongsToMany(DashboardItem::class, 'dashboard_item_user', 'user_id', 'dashboard_item_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\AssignRole;
use Illuminate\Http\Request;
use App\User;
use App\Models\Role;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('role')->get();
        $users = $users->filter( function($user){
            return $user->role->id == 1;
        });

        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::where('name', 'super-admin')->get();
        return view('user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required|string|min:3',
            'last_name' => 'required|string|min:3',
            'user_name' => 'required|string|min:3',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6|confirmed',
            'role' => 'required|integer|exists:roles,id'
        ]);

        User::create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'user_name' => $request->user_name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role_id' => $request->role
        ]);

        return redirect()->route('users.index')->with([
           'status' => 'success',
           'message' => 'User has been created successfully'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all();
        return view('user.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'first_name' => 'required|string|min:3',
            'last_name' => 'required|string|min:3',
            'user_name' => 'required|string|min:3',
            'email' => 'required|email',
            'role' => 'required|integer|exists:roles,id'
        ]);

        $user = User::findOrFail($id);
        $user->update([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'user_name' => $request->user_name,
            'email' => $request->email,
            'role_id' => $request->role
        ]);

        return back()->with([
            'status' => 'success',
            'message' => 'User has been updated successfully'
        ]);;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('users.index')->with([
            'status' => 'success',
            'message' => 'User has been deleted successfully'
        ]);
    }
}

resources/views/user/create.blade.php
@extends('adminlte::page')
@section('title', 'Create User')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Create User</h3>
        </div>
        <form action="{{ route('users.store') }}" method="POST">
            @csrf
        <div class="box-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group {{ $errors->has('first_name') ? 'has-error' : '' }}">
                        <label>First Name</label>
                        <input type="text" name="first_name" class="form-control">
                        @if($errors->has('first_name'))
                            <span class="help-block text-danger">{{ $errors->first('first_name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group {{ $errors->has('last_name') ? 'has-error' : '' }}">
                        <label>Last Name</label>
                        <input type="text" name="last_name" class="form-control">
                        @if($errors->has('last_name'))
                            <span class="help-block text-danger">{{ $errors->first('last_name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group {{ $errors->has('user_name') ? 'has-error' : '' }}">
                        <label>User Name</label>
                        <input type="text" name="user_name" class="form-control">
                        @if($errors->has('user_name'))
                            <span class="help-block text-danger">{{ $errors->first('user_name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                        <label>Email</label>
                        <input type="email" name="email" class="form-control">
                        @if($errors->has('email'))
                            <span class="help-block text-danger">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                        <label>Password</label>
                        <input type="password" name="password" class="form-control">
                        @if($errors->has('password'))
                            <span class="help-block text-danger">{{ $errors->first('password') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                        <label>Confirm Password</label>
                        <input type="password" name="password_confirmation" class="form-control">
                        @if($errors->has('password_confirmation'))
                            <span class="help-block text-danger">{{ $errors->first('password_confirmation') }}</span>
                        @endif
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group {{ $errors->has('assign-roles') ? 'has-error' : '' }}">
                        <label>Role</label>
                        <select class="form-control" name="role">
                            @if(!empty($roles))
                                        @foreach($roles as $role)
                                                <option value="{{ $role->id }}" {{ ($role->id == old('role')) ? 'selected' : '' }}
                                                        selected="selected">{{ $role->name }}</option>
                                        @endforeach
                                    @endif
                        </select>
                        @if($errors->has('role'))
                            <span class="help-block text-danger">{{ $errors->first('role') }}</span>
                        @endif
                    </div>
                </div>
            </div>            
        </div>
        <div class="box-footer">
            <button type="submit" class="btn btn-primary btnTheme">Submit</button>
        </div>
        </form>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit User')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Create User</h3>
        </div>
        <form action="{{ route('users.update', $user->id) }}" method="POST">
            @csrf
            {{ method_field('PUT') }}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('first_name') ? 'has-error' : '' }}">
                            <label>First Name</label>
                            <input type="text" name="first_name" class="form-control" value="{{ $user->first_name }}">
                            @if($errors->has('first_name'))
                                <span class="help-block text-danger">{{ $errors->first('first_name') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('last_name') ? 'has-error' : '' }}">
                            <label>Last Name</label>
                            <input type="text" name="last_name" class="form-control" value="{{ $user->last_name }}">
                            @if($errors->has('last_name'))
                                <span class="help-block text-danger">{{ $errors->first('last_name') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('user_name') ? 'has-error' : '' }}">
                            <label>User Name</label>
                            <input type="text" name="user_name" class="form-control" value="{{ $user->user_name }}">
                            @if($errors->has('user_name'))
                                <span class="help-block text-danger">{{ $errors->first('user_name') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control" value="{{ $user->email }}">
                            @if($errors->has('email'))
                                <span class="help-block text-danger">{{ $errors->first('email') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('role') ? 'has-error' : '' }}">
                            <label>Role</label>
                            <select class="form-control" name="role">
                                @if(!empty($roles))
                                        @foreach($roles as $role)
                                                <option value="{{ $role->id }}" {{ ($role->id == $user->role_id) ? 'selected' : '' }}>{{ $role->name }}</option>
                                        @endforeach
                                    @endif
                            </select>
                            @if($errors->has('assign-roles'))
                                <span class="help-block text-danger">{{ $errors->first('adjuster-roles') }}</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btnTheme">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('adminlte::page')
@section('title', 'All Users')

@section('content')
    <div class="box">
        <div class="box-header">
            <div class="col-md-6">
                <h3 class="box-title">All Users</h3>
            </div>
            <div class="col-md-6 text-right">
                <a href="{{ route('users.create') }}" class="btn btn-primary btnTheme">Create User</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="client" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Sr#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                	@foreach($users as $user)
                	 <tr>
                	 	<td>{{ $loop->iteration }}</td>
                	 	<td>{{ $user->user_name ?? '--' }}</td>
                	 	<td>{{ $user->email }}</td>
                	 	<td>{{ $user->role->name??'--' }}</td>
                       <td>
                       	  <a href="{{ route('users.edit', $user->id) }}"><button class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-pencil"></i></button></a>
                            <a href="#"><button class="btn btn-xs btn-success"><i class="fa fa-eye"></i></button></a>
                            <form action="{{ route('users.destroy', $user->id) }}" method="POST" class="delete_item">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-xs btn-danger" data-toggle="tooltip" title="Delete"><i class="glyphicon glyphicon-remove"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

@push('js')
    <script type="text/javascript">
        $(function () {
            $('#client').DataTable({
                'lengthChange': false,
            })

        });
    </script>
@endpush