routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/cache-clear', function(){
   // \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    \Illuminate\Support\Facades\Artisan::call('migrate');
});
Route::middleware(['auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/test-api', 'TestController@index');
    Route::get('/test-api/cities', 'TestController@getCities');

    Route::resource('/users', 'UserController');
    
    //Route for Master Adjuster

    Route::resource('/adjusters', 'MasterAdjusterController');
    
    Route::post('/adjustermasterslug', 'AjaxController@adjustermasterslug')->name('adjustermasterslug');
    Route::get('/master-fields', 'MasterFieldAccessController@masterfields')->name('masterfields');
    Route::post('/master-fields/store', 'MasterFieldAccessController@store')->name('store');    
    //Routes for Personal Reasons
    Route::resource('/inactive-reasons', 'PersonalInactiveReasonController');
    
    //Routes for state/state service areas
    Route::resource('/states', 'StateController');
    
    //Routes for state/state service areas
    Route::resource('/cities', 'CityController');
    
    //Route for service state area
    Route::resource('/service-state-area', 'ServiceStateAreaController');
    
    //Routes for adjuster grade
    Route::resource('/adjuster-grades', 'AdjusterGradeController');
    
    //Routes for grade reasons
    Route::resource('/grade-reasons', 'GradeReasonController');
    
    //Routes for home states
    Route::resource('/home-state-license', 'AdjusterHomeStateLicenseController');
    Route::get('/home-state-license/single/edit/{state_license}', 'AdjusterHomeStateLicenseController@editSingle')->name('home-state-license-single.edit');
    
    //Route for role
    Route::resource('/roles', 'RoleController');
    
    //Route for search adjuster
    Route::get('/search/adjuster', 'SearchAdjusterController@index')->name('search.adjuster.index');
    Route::post('/search/adjuster', 'SearchAdjusterController@search')->name('search.adjuster');
    
    //Route for supporting forms main file
    Route::get('/supporting-forms', 'SupportingFormController@index')->name('supporting.form.index');
    
    //Routes for Languages
    Route::resource('/languages', 'LanguageController');
    
    //Routes for specialities
    Route::resource('/specialties', 'SpecialityController');
    
    //Route for carriers
    Route::resource('/carriers', 'CarrierController');
    
    //Route for Field Assign Source
    Route::resource('/field-assign-sources', "FieldAssignSourceController");
    
    //Route for Cl Assign Type
    Route::resource('/cl-assign-types', "ClAssignTypeController");

    //Route for personal status
    Route::resource('/personal-status', 'PersonalStatusController');
    
    //Route for Adjuster Correction
    Route::resource('/adjuster-corrections', "AdjusterCorrectionController");
    
    //Route for correction rejections
    Route::resource('/correction-rejections', 'CorrectionRejectionController');
    
    //Route for Log assignments
    Route::resource('/log-assignment', 'LogAssignmentController');

    Route::get('/log-fields', 'LogFieldAccessController@logfields')->name('logfields');
    Route::post('/log-fields/store', 'LogFieldAccessController@logstore')->name('logstore');
    
    //Routes for Claim Status
    Route::resource('/claim-status', 'ClaimStatusController');
    
    //Route for Tabs
    Route::get('/adjuster/{adjuster_id}/home-states', 'TabController@homeStates')->name('tab.adjuster.homestate');
    Route::get('/adjuster/{adjuster_id}/corrections', 'TabController@corrections')->name('tab.adjuster.corrections');
    Route::get('/adjuster/{adjuster_id}/rejections', 'TabController@rejections')->name('tab.adjuster.rejections');
    Route::get('/adjuster/{adjuster_id}/log-assignments', 'TabController@logAssignment')->name('tab.adjuster.log-assignments');
    Route::get('/adjuster/{adjuster_id}/claim-status', 'TabController@claimStatus')->name('tab.adjuster.claim-status');
    
    
    Route::get('/manage-dashboard', 'DashboardItemController@index')->name('dashboard.item.index');
    Route::post('/save-user-dashboard-item', 'DashboardItemController@store')->name('dashboard.item.user.store');

    //ajax routes
    Route::post('/get-cities', 'AjaxController@getCities')->name('get.cities');
    
});

app/Models/LogAssignment.php
<?php

namespace App\Models;

use Carbon\Carbon;
use DateTime;
use Illuminate\Database\Eloquent\Model;

class LogAssignment extends Model
{
    protected $table = 'log_assignments';
    protected $guarded = [];

    // public function carrier(){
    //     return $this->belongsTo(Carrier::class, 'carrier_id', 'id');
    // }

    // public function field_assign_source(){
    //     return $this->belongsTo(FieldAssignSource::class, 'field_assign_source_id', 'id');
    // }

    public function master_adjuster(){
        return $this->belongsTo(MasterAdjuster::class, 'master_adjuster_id', 'id');
    }

    // public function cl_assign_type(){
    //     return $this->belongsTo(ClAssignType::class, 'cl_assign_type_id', 'id');
    // }

    public function state(){
        return $this->belongsTo(State::class, 'state_id', 'id');
    }

    public function city(){
        return $this->belongsTo(City::class, 'city_id', 'id');
    }

    // public function close_type(){
    //     return $this->belongsTo(CloseType::class, 'close_type_id', 'id');

    // }

    public function setDateAttribute($value){
        //$datetime = new DateTime($value);
        $datetime = $value == null ? null : DateTime::createFromFormat('m-d-Y', $value);
        return $this->attributes['date'] = $datetime->format('Y-m-d');
    }

    public function getDateAttribute($value){
        return Carbon::parse($value)->format('m-d-Y');
    }
}

app/Http/Controllers/LogAssignmentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddLogAssignmentRequest;
use App\Http\Requests\StoreLogAssignment;
use App\Models\Carrier;
use App\Models\City;
use App\Models\ClAssignType;
use App\Models\CloseType;
use App\Models\LogFieldAccess;
use App\Models\FieldAssignSource;
use App\Models\LogAssignment;
use App\Models\MasterAdjuster;
use App\Models\State;
use App\Models\StateServiceArea;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class LogAssignmentController extends Controller
{
    public function index(){
        $log_assignments = LogAssignment::all();
        $form_fields =LogFieldAccess::first();

        return view('log-assignment.index', compact('log_assignments','form_fields'));
    }

    public function create(){
        $adjusters = MasterAdjuster::whereHas('types', function(Builder $query){
            $query->where('adjuster_type_id', 1);
        })->get();
        $states = State::all();

        return view('log-assignment.create', compact('adjusters', 'states'));
    }

    public function store(AddLogAssignmentRequest $request){
        LogAssignment::create([
              "claim_number" => $request['claim_number'],
              "tsi_file_number" => $request['tsi_file_number'],
              "master_adjuster_id" => $request['adjuster'],
              "insured" => $request['insured'],
              "state_id" => $request['state'],
              "city_id" => $request['city'],
              "zip_code" => $request['zip'],
              "date" => $request['date'],
              'status' => ($request->status == 'closed') ? 0 : 1
        ]);

        return redirect()->route('log-assignment.index')->with(['status'=> 'success', 'message' => 'Log Assignment has been added.']);
    }


    public function show($id){
        $log_assignment = LogAssignment::findOrFail($id);
        return view('log-assignment.show', compact('log_assignment'));
    }

    public function edit($id){
        $log_assignment = LogAssignment::findOrFail($id);
        $adjusters = MasterAdjuster::whereHas('types', function(Builder $query){
            $query->where('adjuster_type_id', 1);
        })->get();
        $states = State::all();
        $cities = City::all();

        return view('log-assignment.edit', compact('log_assignment','states','adjusters', 'cities'));
    }

    public function update(AddLogAssignmentRequest $request, $id){
        $log_assignment = LogAssignment::findOrFail($id);
        $log_assignment->update([
            "claim_number" => $request['claim_number'],
            "tsi_file_number" => $request['tsi_file_number'],
            "master_adjuster_id" => $request['adjuster'],
            "insured" => $request['insured'],
            "state_id" => $request['state'],
            "city_id" => $request['city'],
            "zip_code" => $request['zip'],
            "date" => $request['date'],
            'status' => ($request->status == 'closed') ? 0 : 1
        ]);

        return back()->with(['status'=> 'success', 'message' => 'Log Assignment has been updated.']);
    }

    public function delete($id){
        $log_assignment = LogAssignment::findOrFail($id);
        $log_assignment->delete();

        return redirect()->route('log-assignment.index')->with(['status'=> 'success', 'message' => 'Log Assignment has been deleted.']);
    }
}

resources/views/log-assignment/edit.blade.php
@extends('adminlte::page')
@section('title', 'Adjuster Log Assignment')

@section('content')
    <div class="box">
        <div class="box-header customHeader">
            <h3 class="box-title">{{ $log_assignment->master_adjuster->getFullName() }} - {{ $log_assignment->master_adjuster->state->name }}</h3>
            <a href="{{ route('adjusters.show', $log_assignment->master_adjuster->id) }}" style="float:right; color:white;">View</a>
        </div>

        <div class="col-md-12" style="padding: 10px;">
            {{-- <div class="col-md-1"></div> --}}
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('adjusters.show', $log_assignment->master_adjuster->id) }}" class="btn btn-primary btnTheme">Adjuster Data</a>
            <a href="{{ route('tab.adjuster.homestate', $log_assignment->master_adjuster->id) }}" class="btn btn-primary btnTheme">State Licenses</a>
            {{-- <div class="col-md-2"></div> --}}
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('tab.adjuster.corrections', $log_assignment->master_adjuster->id) }}" class="btn btn-primary btnTheme">Corrections</a>
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('tab.adjuster.rejections', $log_assignment->master_adjuster->id) }}" class="btn btn-primary btnTheme">Rejections</a>
            {{-- <div class="col-md-2"></div> --}}
            <a href="{{ route('tab.adjuster.log-assignments', $log_assignment->master_adjuster->id) }}" style="background-color: #dd4b39 !important;border-color: #dd4b39 !important;" class="btn btn-primary btnTheme">Claim Log Assignments</a>
            <a href="{{ route('tab.adjuster.claim-status', $log_assignment->master_adjuster->id) }}" class="btn btn-primary btnTheme">Claim Status</a>

        </div>
        <div class="clearfix"></div>
        <form action="{{ route('log-assignment.update', $log_assignment->id) }}" method="POST">
            @csrf
            {{ method_field('PUT') }}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('claim_number') ? 'has-error': '' }}">
                                <label>Claim Number</label>
                                <input type="text" name="claim_number" class="form-control" value="{{ $log_assignment->claim_number }}">
                                @if($errors->has('claim_number'))
                                    <span class="help-block text-danger">{{ $errors->first('claim_number') }}</span>
                                @endif
                            </div>
                        </div>
    
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('tsi_file_number') ? 'has-error': '' }}">
                                <label>TSI File Number</label>
                                <input type="text" name="tsi_file_number" class="form-control" value="{{ $log_assignment->tsi_file_number }}">
                                @if($errors->has('tsi_file_number'))
                                    <span class="help-block text-danger">{{ $errors->first('tsi_file_number') }}</span>
                                @endif
                            </div>
                        </div>
    
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('adjuster') ? 'has-error': '' }}">
                                <label>Adjuster</label>
                                <select name="adjuster" class="form-control">
                                    <option value="">--Select--</option>
                                    @if(!empty($adjusters))
                                        @foreach($adjusters as $adjuster)
                                            <option value="{{ $adjuster->id }}" {{ ($log_assignment->master_adjuster_id == $adjuster->id) ? 'selected' : '' }}>{{ $adjuster->getFullName() }}</option>
                                        @endforeach
                                    @endif
                                </select>
                                @if($errors->has('adjuster'))
                                    <span class="help-block text-danger">{{ $errors->first('adjuster') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('insured') ? 'has-error': '' }}">
                                <label>Insured</label>
                                <input type="text" name="insured" class="form-control" value="{{ $log_assignment->insured }}">
                                @if($errors->has('insured'))
                                    <span class="help-block text-danger">{{ $errors->first('insured') }}</span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('state') ? 'has-error': '' }}">
                                <label>State</label>
                                <select name="state" class="form-control" id="states">
                                    <option value="">--Select--</option>
                                    @if(!empty($states))
                                        @foreach($states as $state)
                                            <option value="{{ $state->id }}" {{ ($log_assignment->state_id == $state->id) ? 'selected' : '' }}>{{ $state->name }}</option>
                                        @endforeach
                                    @endif
                                </select>
                                @if($errors->has('state'))
                                    <span class="help-block text-danger">{{ $errors->first('state') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('city') ? 'has-error': '' }}">
                                <label>City</label>
                                <select name="city" class="form-control">
                                    <option value="">--Select--</option>
                                        @foreach($log_assignment->state->cities as $city)
                                            <option value="{{ $city->id }}" {{ ($log_assignment->city_id == $city->id) ? 'selected' : '' }}>{{ $city->name }}</option>
                                        @endforeach
                                </select>
                                @if($errors->has('city'))
                                    <span class="help-block text-danger">{{ $errors->first('city') }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('zip') ? 'has-error': '' }}">
                                <label>Zip</label>
                                <input type="text" name="zip" class="form-control" value="{{ $log_assignment->zip_code }}">
                                @if($errors->has('zip'))
                                    <span class="help-block text-danger">{{ $errors->first('zip') }}</span>
                                @endif
                            </div>
                        </div>
                    
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('date') ? 'has-error': '' }}">
                            <label>Date</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                <input type="text" class="form-control datepicker" name="date" value="{{ $log_assignment->date }}">
                                @if($errors->has('date'))
                                    <span class="help-block text-danger">{{ $errors->first('date') }}</span>
                                @endif
                            </div>
                        </div>
                        </div>
                    </div>
    
                    <div class="col-md-12">
                        <div class="col-md-3">
                            <div class="form-group {{ $errors->has('status') ? 'has-error': '' }}">
                                <label>Status</label>
                                <select name="status" id="status" class="form-control">
                                    <option value="">Select</option>
                                    <option value="open" {{ ($log_assignment->status == 1) ? 'selected' : '' }}>Open</option>
                                    <option value="close" {{ ($log_assignment->status == 0) ? 'selected' : ''}}>Close</option>
                                </select>
                                @if($errors->has('status'))
                                    <span class="help-block text-danger">{{ $errors->first('status') }}</span>
                                @endif
                            </div>
                        </div>
                    </div>       
                </div>
            </div> 
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btnTheme">Save</button>
            </div>
        </form>
    </div>
@endsection
@push('js')
    <script>
         $("#all_states").change( function(){
            var state = $(this).val();
            $.ajax({
                method: "POST",
                url: "{{ route('get.cities') }}",
                data: {state_id: state, _token: '{{csrf_token()}}'},
                dataType: 'json',
                success: function(response){
                    if(response.status == 'success'){
                        var options = '';
                        options += '<option value="">--Select--</option>';
                        response.cities.forEach( function(data){
                            options += '<option value="'+ data.id +'">'+ data.name +'</option>';
                        });

                        $("#cities").html(options);
                    }
                }
            })
        });
    </script>
@endpush

resources/views/log-assignment/index.blade.php
@extends('adminlte::page')
@section('title', 'All Log Assignments')

@section('content')
    <div class="box">
        <div class="box-header">
            <div class="col-md-6">
                <h3 class="box-title">All Log Assignments</h3>
            </div>
            <div class="col-md-6 text-right">
                <a href="{{ route('log-assignment.create') }}" class="btn btn-primary btnTheme">Create Log Assignments</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="client" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Sr#</th>
                    @if($form_fields->claim_number==true)<th>Claim Number</th>@endif
                    @if($form_fields->master_adjuster_id==true)<th>Adjuster</th>@endif
                    @if($form_fields->tsi_file_number==true)<th>File Number</th>@endif
                    @if($form_fields->city_id==true)<th>City</th>@endif
                    @if($form_fields->state_id==true)<th>State</th>@endif
                    @if($form_fields->zip_code==true)<th>Zip Code</th>@endif
                    @if($form_fields->date==true)<th>Date</th>@endif
                    @if($form_fields->company==true)<th>Company</th>@endif
                    @if($form_fields->status==true)<th>Status</th>@endif
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @if(!empty($log_assignments))
                    @foreach($log_assignments as $log_assignment)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            @if($form_fields->claim_number==true)<td>{{ $log_assignment->claim_number ?? '--' }}</td>@endif
                            @if($form_fields->master_adjuster_id==true)<td>{{ $log_assignment->master_adjuster->getFullName() ?? '--' }}</td> @endif
                            @if($form_fields->tsi_file_number==true)<td>{{ $log_assignment->tsi_file_number ?? '--' }}</td>@endif
                            @if($form_fields->city_id==true)<td>{{ $log_assignment->city_id ?? '--' }}</td>@endif
                            @if($form_fields->state_id==true)<td>{{ $log_assignment->state_id ?? '--' }}</td>@endif
                            @if($form_fields->zip_code==true)<td>{{ $log_assignment->zip_code ?? '--' }}</td>@endif
                            @if($form_fields->date==true)<td>{{ $log_assignment->date ?? '--' }}</td>@endif
                            @if($form_fields->company==true)<td>{{ $log_assignment->company ?? '--' }}</td>@endif
                            @if($form_fields->status==true)<td>{{ ($log_assignment->status == 0) ? 'close' : 'open'}}</td>@endif
                            <td>
                                <a href="{{ route('log-assignment.edit', $log_assignment->id) }}"><button class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-pencil"></i></button></a>
                                <a href="{{ route('log-assignment.show', $log_assignment->id) }}"><button class="btn btn-xs btn-success"><i class="fa fa-eye"></i></button></a>
                                <form action="{{ route('log-assignment.destroy', $log_assignment->id) }}" method="POST" class="delete_item">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-xs btn-danger" data-toggle="tooltip" title="Delete"><i class="glyphicon glyphicon-remove"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>

@endsection

@push('js')
    <script type="text/javascript">
        $(function () {
            $('#client').DataTable({
                'lengthChange': true,
                'pagelength': 10
            })

        });
    </script>
@endpush

resources/views/log-assignment/show.blade.php
@extends('adminlte::page')
@section('title', 'Adjuster Log Assignment')

@section('content')
<div class="box">
            <div class="box-header customHeader">
                <h3 class="box-title">{{ $log_assignment->assign_adjuster->getFullName() }} - {{ $log_assignment->assign_adjuster->state->name }}</h3>
                <a href="{{ route('adjusters.edit', $log_assignment->assign_adjuster->id) }}" style="float:right; color:white;">Edit</a>
            </div>
            <div class="col-md-12" style="padding: 10px;">
                {{-- <div class="col-md-1"></div> --}}
                {{-- <div class="col-md-2"></div> --}}
                <a href="{{ route('adjusters.show', $log_assignment->assign_adjuster->id) }}" class="btn btn-primary btnTheme">Adjuster Data</a>
                {{-- <div class="col-md-2"></div> --}}
                <a href="{{ route('tab.adjuster.homestate', $log_assignment->assign_adjuster->id) }}" class="btn btn-primary btnTheme">State Licenses</a>
                {{-- <div class="col-md-2"></div> --}}
                <a href="{{ route('tab.adjuster.corrections', $log_assignment->assign_adjuster->id) }}" class="btn btn-primary btnTheme">Corrections</a>
                {{-- <div class="col-md-2"></div> --}}
                <a href="{{ route('tab.adjuster.rejections', $log_assignment->assign_adjuster->id) }}" class="btn btn-primary btnTheme">Rejections</a>
                {{-- <div class="col-md-2"></div> --}}
                <a href="{{ route('tab.adjuster.log-assignments', $log_assignment->assign_adjuster->id) }}" style="background-color: #dd4b39 !important;border-color: #dd4b39 !important;" class="btn btn-primary btnTheme">Claim Log Assignments</a>
                <a href="{{ route('tab.adjuster.claim-status', $log_assignment->assign_adjuster->id) }}" class="btn btn-primary btnTheme">Claim Status</a>

            </div>
            <div class="clearfix"></div>
            <div class="box-body table-responsive no-padding">
                <div class="box-header customHeader">
                    <h3 class="box-title"><b>Claim Number: {{ $log_assignment->claim_number}}</b></h3>
                    <a href="{{ route('log-assignment.edit', $log_assignment->id) }}" style="float:right; color:white;">Edit</a>
                </div>
              <table class="table table-bordered tableStyle">
               <tbody>
                <tr>
                  <th>Field Assign Source</th>
                  <td>{{ $log_assignment->field_assign_source->name ?? "-" }}</td>
                </tr>
                <tr>
                    <th>TSI Claim Number</th>
                    <td>{{ $log_assignment->tsi_claim_number ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Cl Assign Type</th>
                    <td>{{ $log_assignment->cl_assign_type->name ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Date Assign Rec</th>
                    <td>{{ $log_assignment->date_assign_rec ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Assign Adjuster FullQ</th>
                    <td>{{ $log_assignment->assign_adjuster->getFullName() ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Assigned</th>
                    <td>{{ ($log_assignment->assigned == 1) ? "Yes" : 'No' }}</td>
                </tr>
                <tr>
                    <th>Insured</th>
                    <td>{{ $log_assignment->insured ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Insured City</th>
                    <td>{{ $log_assignment->insured_city ?? "-" }}</td>
                </tr>
                <tr>
                    <th>State</th>
                    <td>{{ $log_assignment->state->name ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Zip</th>
                    <td>{{ $log_assignment->zip ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Insd Phone</th>
                    <td>{{ $log_assignment->insured_phone_no ?? "-" }}</td>
                </tr>
                 <tr>
                    <th>Carrier</th>
                    <td>{{ $log_assignment->carrier->name ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Co Claim Number</th>
                    <td>{{ $log_assignment->co_claim_number ?? "-" }}</td>
                </tr>
                <tr>
                    <th>CMS</th>
                    <td>{{ ($log_assignment->cms == 1) ? "Yes" : "No" }}</td>
                </tr>
                <tr>
                    <th>Acknowledgement Sent Attic-Musa, Chubb</th>
                    <td>{{ ($log_assignment->acknowledgement == 1) ? "Yes" : "No" }}</td>
                </tr>
                <tr>
                    <th>Date Contacted</th>
                    <td>{{ $log_assignment->date_contacted ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Date Inspected</th>
                    <td>{{ $log_assignment->date_inspected ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Date Report Due</th>
                    <td>{{ $log_assignment->date_report_due ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Date Rep Returned</th>
                    <td>{{ $log_assignment->date_rep_returned ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Date Assign Closed</th>
                    <td>{{ $log_assignment->date_assign_closed ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Close Type</th>
                    <td>{{ $log_assignment->close_type->name ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Date ReOpened</th>
                    <td>{{ $log_assignment->date_reopened ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Date ReClosed</th>
                    <td>{{ $log_assignment->date_reclosed ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Notes</th>
                    <td>{{ $log_assignment->notes ?? "-" }}</td>
                </tr>
                <tr>
                    <th>Maps</th>
                    <td>
                        <a href="{{ $log_assignment->map_link }}" target="_blank">{{ $log_assignment->map_link }}</a>
                    </td>
                </tr>
              </tbody>
            </table>
            </div>
            <!-- /.box-body -->
          </div>
@endsection

@push('css')
<style type="text/css">
.tableStyle th
{
    width: 20%;
}
</style>
@endpush